//! NetEase Cloud Music.
//!
//! # Why a Chinese service is worth a request for an English library
//!
//! Because its coverage is not what its home market suggests. NetEase carries
//! Western pop as thoroughly as it carries Mandopop, and — the part that
//! matters here — a large share of it in `yrc`, their own word-timed format.
//! For any track with a Chinese, Japanese or Korean release it is very often
//! the only provider with word timings at all.
//!
//! It also carries two lanes nobody else here does: `tlyric`, a translation,
//! and `romalrc`, a romanisation. The romanisation is the interesting one.
//! `lib/romanise.ts` refuses to *generate* Japanese and Chinese romanisations
//! because doing it without a morphological dictionary produces plausible
//! nonsense — but this one is not generated by us and not guessed, so taking
//! it breaks no principle that file set out.
//!
//! # About the endpoint
//!
//! Unofficial and undocumented, like the other two non-LRCLIB providers. It
//! needs no key but it does want a `Referer` from its own site, and it answers
//! an unrecognised client with an empty result rather than an error. Every
//! failure here is silent.

use serde::Deserialize;

use super::model::{Hit, Line, Query, Sheet, Word};
use super::{lrc, tidy};

const SOURCE: &str = "NetEase";
const SEARCH: &str = "https://music.163.com/api/search/get";
const LYRIC: &str = "https://music.163.com/api/song/lyric/v1";
const REFERER: &str = "https://music.163.com";

/// Between LRCLIB and Apple Music. The sheets are good; the matching is the
/// weak part, because the search is text and returns covers freely.
const TRUST: u32 = 30;

/// How many search results are looked up in full.
///
/// Each one costs a second request, so this is the number of times we are
/// willing to be wrong about which pressing the search meant. Three is enough
/// for the album cut to be among them when the single ranks first.
const CANDIDATES: usize = 3;

/// How far a lane line may sit from the line it annotates.
///
/// Half a second. The translation and romanisation lanes are timed against the
/// same recording, so they agree exactly far more often than not; the
/// tolerance is for sheets whose lanes were stamped separately.
const LANE_DRIFT: f64 = 0.5;

#[derive(Deserialize)]
struct SearchAnswer {
    result: Option<SearchResult>,
}

#[derive(Deserialize)]
struct SearchResult {
    #[serde(default)]
    songs: Vec<Song>,
}

#[derive(Debug, Clone, Deserialize)]
struct Song {
    id: u64,
    #[serde(default)]
    name: String,
    /// Milliseconds.
    #[serde(default)]
    duration: u64,
    #[serde(default)]
    artists: Vec<Named>,
    album: Option<Named>,
}

#[derive(Debug, Clone, Deserialize)]
struct Named {
    name: Option<String>,
}

#[derive(Deserialize)]
struct Sheets {
    lrc: Option<Verse>,
    /// Word-timed, and the reason this provider is here.
    yrc: Option<Verse>,
    /// A translation.
    tlyric: Option<Verse>,
    /// A romanisation, written by the contributor rather than generated.
    romalrc: Option<Verse>,
    #[serde(default, rename = "pureMusic")]
    pure_music: bool,
}

#[derive(Deserialize)]
struct Verse {
    lyric: Option<String>,
}

pub async fn find(query: &Query) -> Vec<Hit> {
    if query.title.trim().is_empty() {
        return Vec::new();
    }

    let wanted = format!("{} {}", query.title, query.artist);
    let url = format!(
        "{SEARCH}?s={}&type=1&limit=10",
        super::encode(wanted.trim())
    );

    let Ok(answer) = get::<SearchAnswer>(&url).await else {
        return Vec::new();
    };
    let songs = answer.result.map(|result| result.songs).unwrap_or_default();

    // Nearest duration first, then the shortlist. The search ranks by
    // popularity, which is not the same question as "which pressing is this".
    let mut songs = songs;
    if query.duration > 0.0 {
        songs.sort_by(|a, b| {
            drift(a, query.duration)
                .partial_cmp(&drift(b, query.duration))
                .unwrap_or(std::cmp::Ordering::Equal)
        });
    }
    songs.truncate(CANDIDATES);

    let mut hits = Vec::new();
    for song in songs {
        let url = format!(
            "{LYRIC}?id={}&cp=false&lv=0&tv=0&rv=0&kv=0&yv=0&ytv=0&yrv=0",
            song.id
        );
        let Ok(sheets) = get::<Sheets>(&url).await else {
            continue;
        };
        if let Some(hit) = hit(&song, &sheets) {
            hits.push(hit);
        }
    }
    hits
}

fn drift(song: &Song, duration: f64) -> f64 {
    match song.duration > 0 {
        true => (song.duration as f64 / 1000.0 - duration).abs(),
        // An unknown duration sorts last rather than first.
        false => f64::MAX,
    }
}

async fn get<T: serde::de::DeserializeOwned>(url: &str) -> Result<T, String> {
    let response = super::client()?
        .get(url)
        .header("Referer", REFERER)
        .send()
        .await
        .map_err(|error| format!("request failed: {error}"))?;

    let status = response.status();
    if !status.is_success() {
        return Err(format!("{status}"));
    }

    response
        .json::<T>()
        .await
        .map_err(|error| format!("unexpected response: {error}"))
}

fn hit(song: &Song, sheets: &Sheets) -> Option<Hit> {
    let text = |verse: &Option<Verse>| {
        verse
            .as_ref()
            .and_then(|verse| verse.lyric.clone())
            .filter(|text| !text.trim().is_empty())
    };

    // `yrc` first: it is the only one with word timings, and a line-synced
    // sheet from the same track is the same lyric with less in it.
    let mut sheet = text(&sheets.yrc)
        .map(|yrc| parse_yrc(&yrc))
        .filter(|sheet| sheet.synced())
        .or_else(|| text(&sheets.lrc).map(|text| lrc::parse(&text)))
        .unwrap_or(Sheet::None);

    let mut instrumental = sheets.pure_music;
    if let Sheet::Synced(lines) = &mut sheet {
        tidy::behead(lines);
        if tidy::instrumental(lines) {
            instrumental = true;
        } else {
            lane(lines, text(&sheets.tlyric).as_deref(), |line| {
                &mut line.translation
            });
            lane(lines, text(&sheets.romalrc).as_deref(), |line| {
                &mut line.romanised
            });
        }
    }
    if instrumental {
        sheet = Sheet::None;
    }

    if sheet.is_empty() && !instrumental {
        return None;
    }

    Some(Hit {
        title: song.name.clone(),
        artist: song
            .artists
            .iter()
            .filter_map(|artist| artist.name.clone())
            .collect::<Vec<_>>()
            .join(", "),
        album: song.album.as_ref().and_then(|album| album.name.clone()),
        duration: (song.duration > 0).then(|| song.duration as f64 / 1000.0),
        trust: TRUST,
        instrumental,
        sheet,
        source: SOURCE.to_string(),
    })
}

/// Attaches a translation or romanisation lane to the lines it annotates.
///
/// Matched by timestamp rather than by position, because the lanes are not
/// always complete — a sheet often translates the verses and leaves the
/// repeated chorus alone, and pairing those by index would put every
/// translation one line further out than the last.
fn lane(lines: &mut [Line], text: Option<&str>, into: impl Fn(&mut Line) -> &mut String) {
    let Some(text) = text else { return };
    let Sheet::Synced(annotations) = lrc::parse(text) else {
        return;
    };

    for line in lines.iter_mut() {
        let nearest = annotations
            .iter()
            .filter(|other| (other.at - line.at).abs() <= LANE_DRIFT)
            .min_by(|a, b| {
                (a.at - line.at)
                    .abs()
                    .partial_cmp(&(b.at - line.at).abs())
                    .unwrap_or(std::cmp::Ordering::Equal)
            });
        if let Some(found) = nearest {
            *into(line) = found.text.clone();
        }
    }
}

/// Parses `yrc`, NetEase's word-timed format.
///
/// A line is `[startMs,durationMs]` followed by `(atMs,lengthMs,0)word` for
/// each word, where `atMs` is absolute rather than relative to the line. Lines
/// beginning `{` are the credit blocks NetEase stores in the same file as
/// JSON, and are not lyrics.
fn parse_yrc(yrc: &str) -> Sheet {
    let mut lines: Vec<Line> = yrc
        .lines()
        .filter(|line| !line.trim_start().starts_with('{'))
        .filter_map(read_yrc)
        .collect();

    if lines.is_empty() {
        return Sheet::None;
    }
    lrc::normalise(&mut lines);
    Sheet::Synced(lines)
}

fn read_yrc(line: &str) -> Option<Line> {
    let (header, mut rest) = line.trim().strip_prefix('[')?.split_once(']')?;
    let (at, span) = pair(header)?;

    let mut words: Vec<Word> = Vec::new();
    while let Some(open) = rest.find('(') {
        let after = &rest[open + 1..];
        let Some(close) = after.find(')') else { break };
        let Some((word_at, length)) = pair(&after[..close]) else {
            // Not a timing — a literal bracket in the lyric. Skip past it
            // rather than stopping, or the rest of the line is lost.
            rest = &after[close + 1..];
            continue;
        };

        let spoken = &after[close + 1..];
        let text = match spoken.find('(') {
            Some(next) => &spoken[..next],
            None => spoken,
        };
        if !text.trim().is_empty() {
            words.push(Word {
                at: word_at,
                end: word_at + length,
                text: text.trim().to_string(),
            });
        }
        rest = &spoken[text.len()..];
    }

    if words.is_empty() {
        return None;
    }

    let text = words
        .iter()
        .map(|word| word.text.as_str())
        .collect::<Vec<_>>()
        .join(" ");

    Some(Line {
        at,
        end: Some(at + span).filter(|end| *end > at),
        text,
        words,
        voice: Default::default(),
        translation: String::new(),
        romanised: String::new(),
    })
}

/// `12345,678` — two millisecond values, of which only the first two matter.
fn pair(text: &str) -> Option<(f64, f64)> {
    let mut parts = text.split(',');
    let first: f64 = parts.next()?.trim().parse().ok()?;
    let second: f64 = parts.next()?.trim().parse().ok()?;
    if !first.is_finite() || !second.is_finite() || first < 0.0 {
        return None;
    }
    Some((first / 1000.0, second / 1000.0))
}

#[cfg(test)]
mod tests {
    use super::*;

    const YRC: &str = "{\"c\":[{\"tx\":\"作词: Someone\"}]}\n\
[12000,2500](12000,400,0)Fall (12400,500,0)in (12900,1600,0)love\n\
[15000,1000](15000,1000,0)Again";

    fn lines(sheet: &Sheet) -> Vec<Line> {
        match sheet {
            Sheet::Synced(lines) => lines.clone(),
            other => panic!("expected a synced sheet, got {other:?}"),
        }
    }

    #[test]
    fn yrc_words_carry_their_own_timings() {
        let lines = lines(&parse_yrc(YRC));
        assert_eq!(lines.len(), 2);
        assert_eq!(lines[0].text, "Fall in love");
        assert_eq!(lines[0].words.len(), 3);
        assert!((lines[0].words[1].at - 12.4).abs() < 0.001);
    }

    #[test]
    fn a_yrc_line_knows_when_it_ends() {
        let lines = lines(&parse_yrc(YRC));
        assert!((lines[0].end.unwrap() - 14.5).abs() < 0.001);
    }

    #[test]
    fn the_json_credit_block_is_not_a_lyric() {
        let lines = lines(&parse_yrc(YRC));
        assert!(!lines.iter().any(|line| line.text.contains("作词")));
    }

    #[test]
    fn yrc_with_nothing_timed_is_nothing() {
        assert_eq!(parse_yrc("no brackets here"), Sheet::None);
        assert_eq!(parse_yrc(""), Sheet::None);
    }

    #[test]
    fn a_translation_lane_is_matched_by_timestamp() {
        let mut lines = lines(&parse_yrc(YRC));
        lane(
            &mut lines,
            Some("[00:15.00]Otra vez\n[00:12.00]Enamorado"),
            |line| &mut line.translation,
        );
        assert_eq!(lines[0].translation, "Enamorado");
        assert_eq!(lines[1].translation, "Otra vez");
    }

    #[test]
    fn a_partial_lane_does_not_shift_the_rest() {
        // Matched by time rather than by index, so a lane that skips the
        // chorus does not put every later translation one line out.
        let mut lines = lines(&parse_yrc(YRC));
        lane(&mut lines, Some("[00:15.00]Otra vez"), |line| {
            &mut line.translation
        });
        assert_eq!(lines[0].translation, "");
        assert_eq!(lines[1].translation, "Otra vez");
    }

    #[test]
    fn a_lane_line_that_is_nowhere_near_is_not_used() {
        let mut lines = lines(&parse_yrc(YRC));
        lane(&mut lines, Some("[01:40.00]Much later"), |line| {
            &mut line.translation
        });
        assert_eq!(lines[0].translation, "");
    }

    #[test]
    fn the_search_answer_parses() {
        let answer: SearchAnswer = serde_json::from_str(
            r#"{"result":{"songs":[{"id":7,"name":"Song","duration":210000,
                "artists":[{"name":"Band"}],"album":{"name":"Record"}}]}}"#,
        )
        .expect("the documented shape");
        let songs = answer.result.expect("a result").songs;
        assert_eq!(songs[0].id, 7);
        assert_eq!(songs[0].artists[0].name.as_deref(), Some("Band"));
    }

    #[test]
    fn an_empty_search_answer_parses_rather_than_failing() {
        let answer: SearchAnswer = serde_json::from_str("{}").expect("an answer");
        assert!(answer.result.is_none());
    }

    #[test]
    fn a_pure_music_track_is_an_instrumental_hit() {
        let song = Song {
            id: 1,
            name: "Quiet".into(),
            duration: 120_000,
            artists: vec![],
            album: None,
        };
        let sheets = Sheets {
            lrc: None,
            yrc: None,
            tlyric: None,
            romalrc: None,
            pure_music: true,
        };
        let hit = hit(&song, &sheets).expect("a hit");
        assert!(hit.instrumental);
    }
}
