//! Apple Music's TTML, which is where accurate word timings actually live.
//!
//! # Why this format and not another
//!
//! Because it is the only widely-served format that was *authored* with word
//! timings rather than having them added by a listener with a stopwatch. LRC
//! can carry them — the `<mm:ss.xx>` extension — but almost nothing in LRCLIB
//! does, so a karaoke sweep fed only by LRC is a sweep over whole lines
//! pretending to be words. TTML is the fix for that, and it is why the whole
//! provider fan-out was worth building.
//!
//! # What the markup says
//!
//! A `<p>` is a line and a `<span>` inside it is a word, each with `begin` and
//! `end`. Beyond that there are three things worth reading:
//!
//! * `ttm:agent` names the singer, and `<ttm:agent type="person">` in the head
//!   says which agents are people. Two different people on one track is a duet,
//!   and the second one is [`Voice::Counter`].
//! * `ttm:role="x-bg"` marks background vocals — the parenthesised echo behind
//!   the line. They are parsed and then left out of the word list, because
//!   threading them into a single lane of LRC would interleave the echo with
//!   the words it answers.
//! * Translations and romanisations arrive either as `x-translation` /
//!   `x-roman` spans inside the line, or as an `<iTunesMetadata>` block in the
//!   head keyed by `itunes:key`. Both are read; the head wins where both exist,
//!   because that is the one Apple actually populates.
//!
//! # Why a real XML parser here
//!
//! `meta/podcast.rs` scans RSS by hand and explains at length why. The input
//! decides it: podcast feeds are written by thousands of publishers and are
//! malformed often enough that a strict parser rejects one in twenty, whereas
//! this is machine-generated by one publisher. It is also namespaced, and the
//! timing metadata lives in those namespaces — a scanner matching tag names
//! would confuse a `<ttm:agent>` element with an `agent` attribute.

use roxmltree::{Document, Node};

use super::lrc;
use super::model::{Line, Sheet, Voice, Word};

/// The namespace `xml:id` lives in. Fixed by the XML spec, so it is safe to
/// match exactly — unlike the TTML namespaces, whose prefixes vary by exporter.
const XML: &str = "http://www.w3.org/XML/1998/namespace";

/// Roles that are a second lane rather than part of the sung line.
const TRANSLATION: &str = "x-translation";
const ROMAN: &str = "x-roman";
const BACKGROUND: &str = "x-bg";

/// Parses a TTML document into a sheet.
///
/// Returns [`Sheet::None`] rather than an error for markup that parses but
/// holds no lines: an empty answer from one provider is an ordinary event in a
/// fan-out, and there is nothing a caller could usefully do with the
/// distinction.
pub fn parse(xml: &str) -> Sheet {
    let Ok(document) = Document::parse(xml) else {
        return Sheet::None;
    };

    let people = people(&document);
    let lead = lead(&document, &people);
    let asides = asides(&document);

    let mut lines: Vec<Line> = document
        .descendants()
        .filter(|node| node.has_tag_name("p"))
        .filter_map(|paragraph| line(paragraph, lead, &people, &asides))
        .collect();

    if lines.is_empty() {
        return Sheet::None;
    }

    // A document can be well-formed and carry no timings at all — the plain
    // lyric, marked up. Worth keeping as text rather than as a sheet whose
    // every line claims to start at zero.
    if lines
        .iter()
        .all(|line| line.at == 0.0 && line.words.is_empty())
    {
        let text = lines
            .iter()
            .map(|line| line.text.as_str())
            .collect::<Vec<_>>()
            .join("\n");
        return Sheet::Plain(text);
    }

    lrc::normalise(&mut lines);
    Sheet::Synced(lines)
}

fn line(
    paragraph: Node,
    lead: Option<&str>,
    people: &[(String, bool)],
    asides: &[(String, Aside)],
) -> Option<Line> {
    let mut words: Vec<Word> = Vec::new();
    let mut translation = String::new();
    let mut romanised = String::new();

    for span in paragraph
        .descendants()
        .filter(|node| node.has_tag_name("span"))
    {
        let role = attribute(span, "role").unwrap_or_default();
        let text = text_of(span);

        match role {
            TRANSLATION => push(&mut translation, &text),
            ROMAN => push(&mut romanised, &text),
            // Kept out of the word list deliberately. Interleaving the echo
            // with the line it answers is worse than dropping it, and LRC has
            // nowhere else to put it.
            _ if role == BACKGROUND || within_background(span) => {}
            _ => {
                // Only the innermost spans are words. A span wrapping other
                // spans is a grouping, and taking its text as well would put
                // every word on the line twice.
                if span.children().any(|child| child.has_tag_name("span")) {
                    continue;
                }
                let Some(at) = stamp(span, "begin") else {
                    continue;
                };
                if text.is_empty() {
                    continue;
                }
                let end = stamp(span, "end").unwrap_or(at);

                // Apple times *syllables*, not words: "Yesterday" arrives as
                // three spans, `Yes` `ter` `day`. Emitting those as three
                // words puts the lyric on screen as "Yes ter day", because
                // the frontend joins words with a space — and it is right to,
                // since for every other provider a word is a word.
                //
                // The markup does say where the word boundaries are, in the
                // only place it can: the whitespace *between* the spans. A
                // span whose previous sibling is another element continues
                // the word before it; one preceded by text, or by nothing, is
                // starting a new one.
                match continues(span).then(|| words.last_mut()).flatten() {
                    Some(word) => {
                        word.text.push_str(&text);
                        word.end = word.end.max(end);
                    }
                    None => words.push(Word { at, end, text }),
                }
            }
        }
    }

    let text = if words.is_empty() {
        text_of(paragraph)
    } else {
        words
            .iter()
            .map(|word| word.text.as_str())
            .collect::<Vec<_>>()
            .join(" ")
    };

    if text.is_empty() && translation.is_empty() {
        return None;
    }

    let at = stamp(paragraph, "begin")
        .or_else(|| words.first().map(|word| word.at))
        .unwrap_or(0.0);
    let end = stamp(paragraph, "end").or_else(|| words.last().map(|word| word.end));

    // The head's translations win: Apple populates that block and leaves the
    // in-line spans empty far more often than the reverse.
    if let Some(key) = attribute(paragraph, "key") {
        if let Some((_, aside)) = asides.iter().find(|(named, _)| named == key) {
            if !aside.translation.is_empty() {
                translation = aside.translation.clone();
            }
            if !aside.romanised.is_empty() {
                romanised = aside.romanised.clone();
            }
        }
    }

    Some(Line {
        at,
        end: end.map(|end| end.max(at)),
        text,
        words,
        voice: voice(paragraph, lead, people),
        translation,
        romanised,
    })
}

/// Which singer a line belongs to.
///
/// Only a *person* other than the lead counts as a counter voice. Exporters
/// also emit group and "other" agents for chorus and crowd, and treating those
/// as a second singer would paint half a stadium chant as a duet.
fn voice(paragraph: Node, lead: Option<&str>, people: &[(String, bool)]) -> Voice {
    if attribute(paragraph, "role") == Some(BACKGROUND) {
        return Voice::Background;
    }
    let Some(agent) = attribute(paragraph, "agent") else {
        return Voice::Lead;
    };
    match person(people, agent) && Some(agent) != lead {
        true => Voice::Counter,
        false => Voice::Lead,
    }
}

fn person(people: &[(String, bool)], agent: &str) -> bool {
    people
        .iter()
        .any(|(named, is_person)| named == agent && *is_person)
}

fn people(document: &Document) -> Vec<(String, bool)> {
    document
        .descendants()
        .filter(|node| node.has_tag_name("agent"))
        .filter_map(|node| {
            let id = node.attribute((XML, "id"))?;
            Some((id.to_string(), node.attribute("type") == Some("person")))
        })
        .collect()
}

/// The first person to sing, who is the lead by definition.
fn lead<'a>(document: &'a Document<'a>, people: &[(String, bool)]) -> Option<&'a str> {
    document
        .descendants()
        .filter(|node| node.has_tag_name("p"))
        .filter_map(|paragraph| attribute(paragraph, "agent"))
        .find(|agent| person(people, agent))
}

#[derive(Default)]
struct Aside {
    translation: String,
    romanised: String,
}

/// Translation and romanisation lanes from the head, keyed by line.
///
/// `<translation>` and `<transliteration>` blocks hold `<text for="L1">`
/// entries pointing back at the `itunes:key` of a line.
fn asides(document: &Document) -> Vec<(String, Aside)> {
    let mut found: Vec<(String, Aside)> = Vec::new();

    for block in document.descendants() {
        let roman = block.has_tag_name("transliteration");
        if !roman && !block.has_tag_name("translation") {
            continue;
        }

        for entry in block.descendants().filter(|node| node.has_tag_name("text")) {
            let Some(key) = entry.attribute("for") else {
                continue;
            };
            let text = text_of(entry);
            if text.is_empty() {
                continue;
            }

            let slot = match found.iter().position(|(named, _)| named == key) {
                Some(at) => at,
                None => {
                    found.push((key.to_string(), Aside::default()));
                    found.len() - 1
                }
            };
            match roman {
                true => push(&mut found[slot].1.romanised, &text),
                false => push(&mut found[slot].1.translation, &text),
            }
        }
    }

    found
}

/// Whether this span carries on the word the previous one began.
///
/// See the note where it is used. Deliberately conservative: a file that
/// pretty-prints one span per line has whitespace between all of them and is
/// read as one word per span, which is the behaviour every other provider
/// gets and is wrong only in that the sweep is coarser.
fn continues(span: Node) -> bool {
    span.prev_sibling()
        .is_some_and(|previous| previous.is_element())
}

fn within_background(span: Node) -> bool {
    span.ancestors()
        .skip(1)
        .any(|node| attribute(node, "role") == Some(BACKGROUND))
}

/// Reads an attribute by local name, whatever namespace it was declared in.
///
/// `ttm:agent`, `itunes:key` and `ttm:role` are the three that matter, and the
/// prefixes bound to those namespaces vary between exporters. Matching the
/// local name reads all of them; the only cost is that an unprefixed `agent`
/// would also match, and no exporter emits one.
fn attribute<'a>(node: Node<'a, 'a>, name: &str) -> Option<&'a str> {
    node.attributes()
        .find(|attribute| attribute.name() == name)
        .map(|attribute| attribute.value())
}

/// A node's text, with runs of whitespace collapsed.
///
/// TTML is indented markup, so the raw text of a line carries the newlines and
/// spaces of the file's formatting rather than of the lyric.
fn text_of(node: Node) -> String {
    let mut out = String::new();
    // Text *nodes* only. `Node::text()` on an element answers with its first
    // child's text, so walking every descendant and asking each one would
    // count the same characters twice — once for the element and once for the
    // text node inside it, which rendered "Fall" as "FallFall".
    for part in node
        .descendants()
        .filter(|node| node.is_text())
        .filter_map(|node| node.text())
    {
        out.push_str(part);
    }
    out.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn push(into: &mut String, text: &str) {
    if text.is_empty() {
        return;
    }
    if !into.is_empty() {
        into.push(' ');
    }
    into.push_str(text);
}

/// TTML's clock values, in the forms that actually appear.
///
/// `hh:mm:ss.sss`, `mm:ss.sss`, and the offset forms `12.5s` and `1200ms`.
/// Frames (`hh:mm:ss:ff`) are not read: they need the document's frame rate,
/// and no lyric exporter emits them.
fn stamp(node: Node, name: &str) -> Option<f64> {
    let raw = attribute(node, name)?.trim();
    if raw.is_empty() {
        return None;
    }

    if let Some(value) = raw.strip_suffix("ms") {
        return value.parse::<f64>().ok().map(|ms| ms / 1000.0);
    }
    for (suffix, scale) in [("s", 1.0), ("m", 60.0), ("h", 3600.0)] {
        if let Some(value) = raw.strip_suffix(suffix) {
            if let Ok(number) = value.parse::<f64>() {
                return Some(number * scale);
            }
        }
    }

    let mut seconds = 0.0;
    for part in raw.split(':') {
        let part: f64 = part.parse().ok()?;
        seconds = seconds * 60.0 + part;
    }
    seconds.is_finite().then_some(seconds)
}

#[cfg(test)]
mod tests {
    use super::*;

    const DUET: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<tt xmlns="http://www.w3.org/ns/ttml"
    xmlns:ttm="http://www.w3.org/ns/ttml#metadata"
    xmlns:itunes="http://music.apple.com/lyric-ttml-internal">
  <head><metadata>
    <ttm:agent type="person" xml:id="v1"/>
    <ttm:agent type="person" xml:id="v2"/>
    <ttm:agent type="group" xml:id="v3"/>
    <iTunesMetadata>
      <translations>
        <translation type="subtitle" xml:lang="es">
          <text for="L1">Cae enamorado</text>
        </translation>
      </translations>
    </iTunesMetadata>
  </metadata></head>
  <body>
    <div>
      <p begin="00:00:12.000" end="00:00:14.500" ttm:agent="v1" itunes:key="L1">
        <span begin="00:00:12.000" end="00:00:12.400">Fall</span>
        <span begin="00:00:12.400" end="00:00:12.900">in</span>
        <span begin="00:00:12.900" end="00:00:14.500">love</span>
        <span ttm:role="x-bg" begin="00:00:13.000" end="00:00:14.000">
          <span begin="00:00:13.000" end="00:00:14.000">(in love)</span>
        </span>
      </p>
      <p begin="00:00:15.000" end="00:00:17.000" ttm:agent="v2" itunes:key="L2">
        <span begin="00:00:15.000" end="00:00:17.000">Again</span>
      </p>
      <p begin="00:00:18.000" end="00:00:19.000" ttm:agent="v3" itunes:key="L3">
        <span begin="00:00:18.000" end="00:00:19.000">Everybody</span>
      </p>
    </div>
  </body>
</tt>"#;

    fn lines(sheet: &Sheet) -> Vec<Line> {
        match sheet {
            Sheet::Synced(lines) => lines.clone(),
            other => panic!("expected a synced sheet, got {other:?}"),
        }
    }

    #[test]
    fn spans_become_words_with_their_own_timings() {
        let lines = lines(&parse(DUET));
        assert_eq!(lines[0].text, "Fall in love");
        assert_eq!(lines[0].words.len(), 3);
        assert!((lines[0].words[1].at - 12.4).abs() < 0.001);
        assert!((lines[0].words[2].end - 14.5).abs() < 0.001);
    }

    #[test]
    fn background_vocals_stay_out_of_the_sung_line() {
        // Threading the echo into the same lane would interleave it with the
        // words it answers.
        let lines = lines(&parse(DUET));
        assert!(
            !lines[0].text.contains("(in love)"),
            "got {}",
            lines[0].text
        );
        assert_eq!(lines[0].words.len(), 3);
    }

    #[test]
    fn a_second_person_singing_is_a_counter_voice() {
        let lines = lines(&parse(DUET));
        assert_eq!(lines[0].voice, Voice::Lead);
        assert_eq!(lines[1].voice, Voice::Counter);
    }

    #[test]
    fn a_group_agent_is_not_a_second_singer() {
        // Otherwise a crowd chant is painted as a duet.
        assert_eq!(lines(&parse(DUET))[2].voice, Voice::Lead);
    }

    #[test]
    fn the_head_translation_is_matched_to_its_line_by_key() {
        assert_eq!(lines(&parse(DUET))[0].translation, "Cae enamorado");
    }

    #[test]
    fn a_line_with_no_translation_keeps_an_empty_one() {
        assert_eq!(lines(&parse(DUET))[1].translation, "");
    }

    #[test]
    fn syllable_spans_are_joined_back_into_one_word() {
        // Apple times syllables. Left apart, "Yesterday" reaches the screen as
        // "Yes ter day", because the frontend joins words with a space.
        let xml = concat!(
            r#"<tt xmlns="http://www.w3.org/ns/ttml"><body><div>"#,
            r#"<p begin="5.25s" end="7.12s">"#,
            r#"<span begin="5.25s" end="5.65s">Yes</span>"#,
            r#"<span begin="5.65s" end="5.80s">ter</span>"#,
            r#"<span begin="5.80s" end="7.12s">day</span>"#,
            r#"</p></div></body></tt>"#
        );
        let lines = lines(&parse(xml));
        assert_eq!(lines[0].text, "Yesterday");
        assert_eq!(lines[0].words.len(), 1);
        // And it is timed across the whole word, not just the first syllable.
        assert!((lines[0].words[0].at - 5.25).abs() < 0.001);
        assert!((lines[0].words[0].end - 7.12).abs() < 0.001);
    }

    #[test]
    fn whitespace_between_spans_still_separates_words() {
        let xml = concat!(
            r#"<tt xmlns="http://www.w3.org/ns/ttml"><body><div>"#,
            r#"<p begin="1s" end="3s">"#,
            r#"<span begin="1s" end="1.5s">All</span> "#,
            r#"<span begin="1.5s" end="2s">my</span> "#,
            r#"<span begin="2s" end="3s">trou</span>"#,
            r#"<span begin="3s" end="3.5s">bles</span>"#,
            r#"</p></div></body></tt>"#
        );
        let lines = lines(&parse(xml));
        assert_eq!(lines[0].text, "All my troubles");
        assert_eq!(lines[0].words.len(), 3);
    }

    #[test]
    fn a_wrapping_span_does_not_duplicate_its_words() {
        let xml = r#"<tt xmlns="http://www.w3.org/ns/ttml"><body><div>
          <p begin="1s" end="2s"><span begin="1s" end="2s">
            <span begin="1s" end="1.5s">One</span>
            <span begin="1.5s" end="2s">Two</span>
          </span></p></div></body></tt>"#;
        let lines = lines(&parse(xml));
        assert_eq!(lines[0].text, "One Two");
    }

    #[test]
    fn offset_clock_values_parse() {
        let xml = r#"<tt xmlns="http://www.w3.org/ns/ttml"><body><div>
          <p begin="1500ms" end="2.5s"><span begin="1500ms" end="2.5s">Word</span>
          </p></div></body></tt>"#;
        let lines = lines(&parse(xml));
        assert!((lines[0].at - 1.5).abs() < 0.001);
        assert!((lines[0].end.unwrap() - 2.5).abs() < 0.001);
    }

    #[test]
    fn markup_with_no_timings_is_kept_as_text() {
        let xml = r#"<tt xmlns="http://www.w3.org/ns/ttml"><body><div>
          <p>Just a line</p><p>And another</p></div></body></tt>"#;
        assert_eq!(parse(xml), Sheet::Plain("Just a line\nAnd another".into()));
    }

    #[test]
    fn broken_markup_is_nothing_rather_than_a_panic() {
        assert_eq!(parse("<tt><body><div><p>unclosed"), Sheet::None);
        assert_eq!(parse(""), Sheet::None);
    }

    #[test]
    fn the_indentation_of_the_file_is_not_part_of_the_lyric() {
        let xml = "<tt xmlns=\"http://www.w3.org/ns/ttml\"><body><div>\n  <p begin=\"1s\">\n    Spread   over\n    lines\n  </p>\n</div></body></tt>";
        assert_eq!(lines(&parse(xml))[0].text, "Spread over lines");
    }
}
